user_authentication/learn_pwd/urls.py
from django.urls import path
from learn_pwd import views

#TEMPLATE URLs
app_name = 'learn_pwd'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login')

]

user_authentication/user_authentication/urls.py
from django.contrib import admin
from django.urls import path,include
from learn_pwd import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('learn_pwd/',include('learn_pwd.urls')),
    path('',views.user_logout,name='logout'),
    path('',views.special,name='special')
]

user_authentication/learn_pwd/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User,on_delete=models.CASCADE,)


    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

user_authentication/learn_pwd/forms.py
from django import forms
from django.contrib.auth.models import User
from learn_pwd.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

user_authentication/learn_pwd/views.py
from django.shortcuts import render
from learn_pwd.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request,'learn_pwd/index.html')



@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponseRedirect("you are loggedin NICE")



def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
                profile.save()

                registered = True
            else:
                print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'learn_pwd/registration.html',{'user_form':user_form,
                                'profile_form':profile_form,
                                'registered':registered})



def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not ACTIVE")
        else:
            print("Some one tried to login and failed")
            print("username: {} and password: {}".format(username,password))
            return HttpResponse("invalid login details !!")
    else:
        return render(request,'learn_pwd/login.html',{})

user_authentication/templates/learn_pwd/basic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top'>
    <!-- <nav class = "navbar navbar-inverse navbar-fixed-top"> -->
      <div class="container">
        <ul class="nav justify-content-center">
          <li> <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a> </li>
          <li> <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>
          <li> <a class="navbar-link" href="{% url 'learn_pwd:register' %}">Register</a> </li>

          {% if user.is_authenticated %}
            <li> <a class='navbar-link' href="{% url 'logout' %}">Logout</a> </li>
          {% else %}
            <li> <a class='navbar-link' href="{% url 'learn_pwd:user_login' %}">Login</a> </li>
          {% endif %}


      </ul>
    </div>
  </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}

    </div>

  </body>
</html>

user_authentication/templates/learn_pwd/index.html
<!DOCTYPE html>
{% extends "learn_pwd/basic.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Django Level Five</h1>
</div>
{% endblock %}

user_authentication/templates/learn_pwd/login.html
{% extends 'learn_pwd/basic.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login </h1>

  <form action="{% url 'learn_pwd:user_login' %}" method="post">
    {% csrf_token %}

    <label for="username">UserName: </label>
    <input type="text" name="username" placeholder="Enter UserName">

    <label for="password">Password: </label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">

  </form>
</div>
{% endblock %}

user_authentication/templates/learn_pwd/registration.html
<!DOCTYPE html>
{% extends "learn_pwd/basic.html" %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for Registreing!!</h1>
  {% else %}
    <h1>Register here</h1>
    <h3>Please fill in the form!!</h3>

    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>

  {% endif %}
</div>
{% endblock %}